import { defineAction } from 'astro:actions';
import { z } from 'astro:schema';

export const createReportDraft = defineAction({
  input: z.object({
    didContent: z.string(),
    thoughtContent: z.string(),
    currentContent: z.string(),
  }),
  handler: async ({ didContent, thoughtContent, currentContent }) => {
    await new Promise(resolve => setTimeout(resolve, 2000));

    const reportContent = `## Daily Report Draft\n\n### What I Did Today:\n${didContent}\n\n### My Thoughts:\n${thoughtContent}\n\n---\n*This is a draft generated by the AI assistant.*`;

    return {
      reportContent,
    };
  },
})