// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyReport struct {
	ID         int64
	UserID     int64
	TeamID     int64
	ReportDate pgtype.Date
	Content    string
	Status     string
	CreatedAt  int64
	UpdatedAt  int64
}

type GithubActivity struct {
	ID             int64
	UserID         int64
	EventID        string
	Type           string
	Url            string
	RepositoryName pgtype.Text
	Payload        []byte
	CreatedAt      int64
}

type GithubIntegration struct {
	ID                   int64
	UserID               int64
	AccessToken          []byte
	RefreshToken         []byte
	Scopes               pgtype.Text
	GithubUsername       int32
	LastProcessedEventID pgtype.Text
	CreatedAt            int64
	UpdatedAt            int64
}

type GithubPollingState struct {
	ID                   int64
	UserID               int64
	LastProcessedEventID pgtype.Text
	CreatedAt            int64
	UpdatedAt            int64
}

type PrivateReflection struct {
	ID             int64
	UserID         int64
	TeamID         int64
	ReflectionDate pgtype.Date
	DidContent     pgtype.Text
	ThoughtContent pgtype.Text
	CreatedAt      int64
	UpdatedAt      int64
}

type SlackActivity struct {
	ID               int64
	UserID           int64
	SlackUserID      pgtype.Text
	Message          string
	Url              string
	ChannelID        pgtype.Text
	MessageTimestamp pgtype.Text
	CreatedAt        int64
}

type SlackIntegration struct {
	ID           int64
	UserID       int64
	AccessToken  []byte
	RefreshToken []byte
	Scopes       pgtype.Text
	SlackUserID  string
	TeamID       string
	CreatedAt    int64
	UpdatedAt    int64
}

type SlackIntegrationChannel struct {
	ID                 int64
	SlackIntegrationID int64
	ChannelID          string
}

type Team struct {
	ID        int64
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type TeamMember struct {
	ID        int64
	UserID    int64
	TeamID    int64
	CreatedAt int64
}

type TrelloActivity struct {
	ID        int64
	UserID    int64
	Type      string
	Content   string
	Url       string
	BoardID   pgtype.Text
	ListID    pgtype.Text
	CardID    pgtype.Text
	CreatedAt int64
}

type TrelloIntegration struct {
	ID        int64
	UserID    int64
	Token     string
	Secret    pgtype.Text
	CreatedAt int64
	UpdatedAt int64
}

type User struct {
	ID              int64
	GithubID        int32
	GithubUsername  string
	Email           pgtype.Text
	AvatarUrl       string
	UserRole        string
	CreatedAt       int64
	UpdatedAt       int64
	LastCollectedAt int64
}
