// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: slack_activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateSlackActivitiesParams struct {
	UserID           int64
	SlackUserID      pgtype.Text
	Message          string
	Url              string
	ChannelID        pgtype.Text
	MessageTimestamp pgtype.Text
	CreatedAt        int64
}

const updateSlackIntegrationToken = `-- name: UpdateSlackIntegrationToken :exec
UPDATE slack_integrations
SET access_token = $1, refresh_token = $2, updated_at = $3
WHERE user_id = $4
`

type UpdateSlackIntegrationTokenParams struct {
	AccessToken  []byte
	RefreshToken []byte
	UpdatedAt    int64
	UserID       int64
}

func (q *Queries) UpdateSlackIntegrationToken(ctx context.Context, arg UpdateSlackIntegrationTokenParams) error {
	_, err := q.db.Exec(ctx, updateSlackIntegrationToken,
		arg.AccessToken,
		arg.RefreshToken,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}
